### ISSUE TITLE
[Improvement] Add Option to set own Open Exchange Rate App ID

### ISSUE THREAD

**Issue by bennokress** [plummm/alfred3-workflow-CurrencyX#10]
In the README you mention to replace the Default App ID in order to save you (and all default users) from hitting the rate limit on the Open Exchange Rate API, but finding where to set that inside your workflow is not quite straightforward. Maybe adding an option in the import dialog could help.

For now, if someone is searching where to set it: it's `self.id` (line 18) in exchange.py …

**Comment by plummm** [comment]
It would be a great work for adding such an option, but I don't have any macOS device for now.
I'm so happy if anyone could do it and I'll merge it to the master branch.

BTW, I suggest globally search for my id `48c5e363909e4a2bba48937790c365e7` to replace since I found one in the update.py, I don't remember if there are any other remains. (Yes, the design is ugly, I hope to reconstruct all code as I have a MacBook again.

**Comment by plummm** [comment]
For a short inspection, I only find two places contain the id
https://github.com/plummm/alfred3-workflow-CurrencyX/blob/f59fe04f8728b9c16436d8283dab60bf4a41aa1c/update.py#L10
https://github.com/plummm/alfred3-workflow-CurrencyX/blob/f59fe04f8728b9c16436d8283dab60bf4a41aa1c/exchange.py#L18

It should work after replacing those two lines
