### ISSUE TITLE
Syntax not working

### ISSUE THREAD

**Issue by ribice** [plummm/alfred3-workflow-CurrencyX#3]
For some reasons, I redownloaded your tool from Packal yesterday and I'm now facing issues.

This used to work, but requires no space now:
![image](https://user-images.githubusercontent.com/5403700/41307457-82ff2554-6e79-11e8-9acd-268c48fce255.png)

![image](https://user-images.githubusercontent.com/5403700/41307467-8ce8d3ee-6e79-11e8-83a8-34faf6a96fef.png)

Not sure what this is:

![image](https://user-images.githubusercontent.com/5403700/41307488-a0021a6c-6e79-11e8-9968-e282218f1e13.png)

This does not work (most important feature for me):

![image](https://user-images.githubusercontent.com/5403700/41307498-a8ef388a-6e79-11e8-8258-4dd87a753651.png)

**Comment by plummm** [comment]
It seems like you didn't `cy-add` bam, use `cy` to see if bam on the panel.
If bam doesn't exist, use `cy-add bam` to add bam to the panel.

`cy [number] [dest_currency]` means convert number of **base currency** into dest_currency
if you want to set bam as the base currency, use `cy-base bam`
`cy [number][src_currency]`(without space) means convert number of src_currency into currencies on the panel.
`cy [number] [src_currency] [dest_currency]` does not work because you doesn't add bam into the panel, pleas use `cy-add bam`, this maybe a bug, I will fix it later
